const optionsDefs = [
  {
    name: "out",
    type: String,
    defaultValue: "."
  },
  {
    name: "groupId",
    type: String,
    defaultValue: "com.example"
  },
  {
    name: "artifactId",
    type: String,
    defaultValue: "demo"
  },
  {
    name: "package",
    type: String,
    defaultValue: "com.example.demo"
  },
  {
    name: "name",
    type: String,
    defaultValue: "demo"
  },
  {
    name: "desc",
    defaultValue: "Simple project generated by simple-spring-gen",
    type: String
  },
  {
    name: "restapi",
    defaultValue: false,
    type: Boolean
  },
  {
    name: "grpc",
    defaultValue: false,
    type: Boolean
  },
  {
    name: "jpa",
    defaultValue: false,
    type: Boolean
  },
  {
    name: "kafka",
    defaultValue: false,
    type: Boolean
  }
];

module.exports = optionsDefs;